### ISSUE TITLE
Missing org.apache.httpcomponents:httpclient dependency

### ISSUE THREAD

**Issue by cberg-zalando** [zalando-stups/stups-spring-oauth2-support#14]
When creating the default `RestTemplate` in `TokenInfoResourceServerTokenServices::buildRestTemplate` you explicitly request the implementation using Apache HttpClient, but you don't specify the dependency in the POM.

If a user of this project does not accidentally have added it as direct or transitive dependency, the application will fail with a `ClassCastException` at runtime.

**Comment by jbellmann** [comment]
Hi Christoph,

with the [latest release](https://github.com/zalando-stups/stups-spring-oauth2-support/releases/tag/1.0.10) we try to select the ClientHttpRequestFactory depending on what is in your classpath. So if you have 'org.apache.httpcomponents-httpclient' in your classpath we use that, otherwise the default.

Please let us know if you have any errors with the release. Then pleases reopen this issue.
