### ISSUE TITLE
OAuth2Exception Wrapping

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando-stups/stups-spring-oauth2-support#69]
Up until https://github.com/zalando-stups/stups-spring-oauth2-support/pull/27 exceptions fetching the token information were wrapped in an `OAuth2Exception`. This enables handling by Spring's authentication facilities, in the end resulting in a `HTTP 40x` response.

Currently exceptions (e.g. timeout to token-info) are propagated to the servlet container and handled via error page semantics, mostly resulting in the container's default `500` error page.

Shouldn't we "hide" failures to resolve again by wrapping them in an `OAuth2Exception`?

**Comment by jbellmann** [comment]
A quick fix for that would be to wrap the used TokenInfoRequestExecutor:

```
    @Bean
    public ResourceServerTokenServices resourceServerTokenServices() {
        return new TokenInfoResourceServerTokenServices(new TokenInfoRequestExecutor() {
            private final TokenInfoRequestExecutor delegate = new DefaultTokenInfoRequestExecutor(tokenInfoUri, DefaultTokenInfoRequestExecutor.buildRestTemplate(TokenResponseErrorHandler.getDefault()));

            @Override
            public Map<String, Object> getMap(String accessToken) {
                try {
                    return delegate.getMap(accessToken);
                } catch (ResourceAccessException e) {
                    Map<String, Object> map = new HashMap<>();
                    map.put("error", "Read timed out");
                    return map;
                }
            }
        });
    }
```

`ResourceAccessException` signals IO-Exceptions.
Putting a key `error` into the map or return `null` instead will be handled by throwing a `InvalidTokenException` and so returning a 401 as expected.

Would be cool to have some more opinions here about what is expected behaviour for such kind of errors.

**Comment by lukasniemeier-zalando** [comment]
Out of the three default Spring OAuth2 `ResourceServerTokenServices`, only the `UserInfoTokenServices` [catches exceptions on the remote call](https://github.com/spring-projects/spring-security-oauth2-boot/blob/master/spring-security-oauth2-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/UserInfoTokenServices.java#L148-L153) and wraps them into an `InvalidTokenException`.

I don't see anything specified about this part in the relevant [RFC](https://tools.ietf.org/html/rfc7662).

**Comment by ctirs** [comment]
We had a problem with that as well.
Due to receiving a bad gateway exception from tokeninfo, micrometer interpreted that as outcome=Exception, Status=200

which made it hard to identify that actually we had a problem with the tokeninfo and not with some other ressource

**Comment by thomasabraham** [comment]
Is this ticket still in progress?
I'm here because of bug report in a service that uses `stups-spring-oauth2-server`.
When the `tokenInfoEndpoint` is not available, it results in an `InvalidTokenException` with HTTP `401` as status code. 
This indicates to the client that it should fetch a new token and retry; which could make the situation worse by adding more requests to a service that is probably overloaded. Ideally the service should return a `503` when the `tokenInfoEndpoint` is  unreachable.
